Repository uwec-innovation-labs/energyDashboard, pull requests merged in 2019-04, with the labels that each got.

#95 48 tie to api
  api/README.md
  api/current_tables.ods
  api/server.js
  api/sqlData.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Home.js
  frontend/src/components/Layout.js
  frontend/src/components/ScatterPlot.js
  frontend/src/styles/App.scss
Labels: review

#97 remove legacy files
  DSC_Solar.xlsx
  LIBSOL_2yr.xlsx
  api/CSV/DSC_Solar.csv
  api/CSV/buildings.csv
  api/CSV/readData.js
  api/CSV/schema.js
  api/CSV/tiny.csv
Labels: review

#99 98 fix month scale
  frontend/src/components/GraphNavigation.js
  frontend/src/components/Home.js
  frontend/src/components/ScatterPlot.js
  frontend/src/helpers/APIFrame.js
  frontend/src/helpers/GraphBuilder.js
  frontend/src/styles/App.scss
Labels: review

#101 Fixes time bug
  api/sqlData.js
  frontend/src/components/GraphNavigation.js
  frontend/src/components/ScatterPlot.js
  frontend/src/helpers/APIFrame.js
  frontend/src/helpers/GraphBuilder.js
Labels: review

#112 Connect stat cards
  api/README.md
  api/notes
  api/package-lock.json
  api/package.json
  api/server.js
  api/sqlData.js
  api/sqlSchema.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Dashboard.js
  frontend/src/components/GraphNavigation.js
  frontend/src/components/Home.js
  frontend/src/components/ScatterPlot.js
  frontend/src/helpers/APIFrame.js
  frontend/src/styles/App.scss
Labels: enhancement, front-end, review

#113 Change axios URL's
  frontend/src/helpers/APIFrame.js
Labels: Energy Dashboard, front-end, review

#114 Removes old dependencies
  api/package-lock.json
  api/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/helpers/APIFrame.js
  package-lock.json
Labels: review

#115 Newer schema
  api/README.md
  api/sqlData.js
  api/sqlSchema.js
Labels: review

#116 Average error
  api/sqlData.js
  api/sqlSchema.js
Labels: review
