Repository uwec-innovation-labs/energyDashboard, pull requests merged in 2019-03, with the labels that each got.

#29 Download Framework
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/AppNav.js
  frontend/src/components/Export.js
  frontend/src/components/Home.js
  frontend/src/components/Layout.js
  frontend/src/styles/App.css
Labels: front-end, review

#28 Make scatter plot
  frontend/src/components/Home.js
  frontend/src/components/ScatterPlot.js
  frontend/src/styles/App.css
Labels: review

#30 Fix Export Button
  frontend/src/components/Export.js
Labels: review

#32 add favicon & manifest update
  frontend/public/favicon.ico
  frontend/public/manifest.json
Labels: review

#35 Fixes download button.
  frontend/package-lock.json
  frontend/src/components/Export.js
  frontend/src/styles/App.css
Labels: front-end, review

#36 Adds SCSS and changes imports to scss vs css
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/AppNav.js
  frontend/src/components/BarGraph.js
  frontend/src/components/Dashboard.js
  frontend/src/components/Export.js
  frontend/src/components/FooterBar.js
  frontend/src/components/Home.js
  frontend/src/components/PrivacyPolicy.js
  frontend/src/components/ScatterPlot.js
  frontend/src/components/TestGraph.js
  frontend/src/components/Widget.js
  frontend/src/components/WidgetBar.js
  frontend/src/index.js
  frontend/src/styles/App.scss
  frontend/src/styles/components/colors.scss
  frontend/src/styles/index.css
Labels: review

#40 Fixes FooterBar position and adds link to privacy policy
  frontend/src/App.js
  frontend/src/components/PrivacyPolicy.js
  frontend/src/styles/App.scss
Labels: review

#42 Make scatterplot container scalable
  frontend/src/components/Home.js
  frontend/src/components/ScatterPlot.js
  frontend/src/styles/App.scss
Labels: enhancement, front-end, review

#58 Adds title and fixes position math
  frontend/src/components/ScatterPlot.js
Labels: review

#61 Adds GraphQL
  api/DSC_Solar.csv
  api/package-lock.json
  api/package.json
  api/server.js
  api/sqlConnect.js
  api/sqlData.js
  api/sqlSchema.js
  energy/README
  energy/dataController.js
  energy/energy.html
  energy/energyRoutes.js
  energy/getData.js
  energy/package.json
  energy/tiny.csv
Labels: review

#80 Katie
  api/README.md
  api/current_tables.ods
  api/notes
  api/package-lock.json
  api/package.json
  api/server.js
  api/sqlConnect.js
  api/sqlData.js
  api/sqlSchema.js
Labels: review

#93 Comp averages
  api/README.md
  api/server.js
  api/sqlData.js
  api/sqlSchema.js
Labels: review
